### ISSUE TITLE
This is bad, and you should know better.

### ISSUE THREAD

**Issue by leejo** [danielmiessler/GitHubRating#1]
Sorry Daniel, i have to call you out on this one; this is bad, and you should know better. You're trying to reduce something to a single figure when it's not that simple. I worry that people will treat this as a serious tool, rather than seeing it as what it really is: pandering to meaningless gamification bullshit. I would hope anyone in a serious position with regards to hiring policy would not be that blind.

Even if this is serious it doesn't meet the required goal and you're using the wrong tool to do it, i.e. github. Even if we let _that_ slide the way you're weighting the factors is completely arbitrary.

Follower count is weighted at x5? Yet this tell you nothing about _how much coding they actually do_.

Repository count should be useful right? Wrong. You're including all repositories, so that includes forks. That's not the problem here, since a repository again tells you nothing about _how much coding they actually do_. Let's pick through your own repositories (sources, not forks) to demonstrate that:
- Personal - not coding
- mobiletools - empty
- SecLists - i see a lot of content here, but very little code
- FreeWill_TwoLever_Argument - two if statements in a for loop
- TeamShuffle - a one liner
- GeoHarvest - a one liner
- iptables - configuration, not coding
- nginx - configuration, not coding
- vim - configuration, not coding
- Restaurants - not coding
- WorkDay - not coding
- Books - not coding
- tmux - configuration, not coding
- CTFSolutionTypes - not pushed to in at least 1 year
- LifeOpt - not coding
- BugOutBag - not pushed to in at least 1 year
- DNSHarvester - not pushed to in at least 1 year
- CertExpirationCheck - not pushed to in at least 1 year
- Self - not coding
- Dicematch - not pushed to in at least 2 years
- Statraises - not pushed to in at least 2 years
- Source2URL - not pushed to in at least 2 years
- mst - not pushed to in at least 5 years
- hostfind - not pushed to in at least 5 years
- mhp - not pushed to in at least 5 years
- diceroll - not pushed to in at least 5 years
- gscour - not pushed to in at least 5 years
- geoip - not pushed to in at least 5 years
- GitHubRating - this repo, and ironically the only one i can find that has been updated recently and actually contains more than a few lines of code

The only meaningful number the script uses is the contribution activity, and even that is flawed - contribution history contains issues raised as well as commits. Issues raised again tells you nothing about _how much coding they actually do_. There's also the fact that the contribution activity doesn't include private repositories, nor does it include commits not merged to master. Also the contribution history being on a commit basis does not really tell you _how much coding they actually do_ given a commit could be anything from empty to thousands of lines of code.

Anyone with the technical knowledge to git clone this repo and run the command should be able to see that it is meaningless, but i worry that others might not.

**Comment by ismailsunni** [comment]
:+1:

**Comment by leejo** [comment]
Closing this because it appears in my issues list. I still think this is a bad idea.
